// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.50.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names, invalid_use_of_internal_member

import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';
import 'package:uuid/uuid.dart';
import 'bridge_generated_1.dart';
export 'bridge_generated_1.dart';
import 'package:meta/meta.dart';

class ApiDbPlatform extends FlutterRustBridgeBase<ApiDbWire> with FlutterRustBridgeSetupMixin {
  ApiDbPlatform(FutureOr<WasmModule> dylib) : super(ApiDbWire(dylib)) {
    setupMixinConstructor();
  }
  Future<void> setup() => inner.init;
// Section: api2wire

// Section: finalizer

}

// Section: WASM wire module

@JS('wasm_bindgen')
external ApiDbWasmModule get wasmModule;

@JS()
@anonymous
class ApiDbWasmModule implements WasmModule {
  external Object /* Promise */ call([String? moduleName]);
  external ApiDbWasmModule bind(dynamic thisArg, String moduleName);
  external void wire_get_db(NativePortType port_);
}

// Section: WASM wire connector

class ApiDbWire extends FlutterRustBridgeWasmWireBase<ApiDbWasmModule> {
  ApiDbWire(FutureOr<WasmModule> module) : super(WasmModule.cast<ApiDbWasmModule>(module));

  void wire_get_db(NativePortType port_) => wasmModule.wire_get_db(port_);
}
